async function Fortune() {

    /*    const response = await fetch("https://inspirobot.me/api?generateFlow=1");
        const movies = await response.json();
        console.log(movies);
    */
    const FortuneCookie = [
        "Eine Reise von tausend Meilen beginnt mit einem einzigen Schritt.",
        "Das Glück liegt oft in kleinen Dingen.",
        "Folge deinem Herzen, es kennt den Weg.",
        "Eine neue Herausforderung bringt neue Möglichkeiten.",
        "Der Erfolg kommt zu denen, die daran glauben.",
        "Jeder Tag ist ein Geschenk, nutze ihn weise.",
        "Vertrauen ist der Schlüssel zu allen Türen.",
        "Ein Lächeln öffnet Herzen.",
        "Geduld bringt Rosen.",
        "Veränderungen bedeuten Wachstum.",
        "Dein Mut wird belohnt werden.",
        "Die beste Zeit ist jetzt.",
        "Freunde sind der Schatz des Lebens.",
        "Glaube an Wunder, sie geschehen jeden Tag.",
        "Jeder Moment zählt.",
        "Sei du selbst, alle anderen gibt es schon.",
        "Ein neuer Anfang wartet auf dich.",
        "Jeder Tag ist eine neue Chance.",
        "Sei dankbar für das, was du hast.",
        "Die Liebe wird dir neue Türen öffnen.",
        "Lebe im Hier und Jetzt.",
        "Wer wagt, gewinnt.",
        "Kleine Taten können Großes bewirken.",
        "Du bist der Architekt deines Lebens.",
        "Veränderungen bringen frischen Wind.",
        "Lass die Vergangenheit los und schau nach vorn.",
        "Erfolg ist das Ergebnis harter Arbeit.",
        "Glaube an deine Träume.",
        "Dein inneres Licht strahlt am hellsten.",
        "Jeder Tag birgt eine neue Möglichkeit.",
        "Genieße die kleinen Freuden des Lebens.",
        "Gute Dinge kommen zu denen, die warten.",
        "Dein Mut wird belohnt werden.",
        "Die Zukunft ist, was du daraus machst.",
        "Lächle und die Welt lächelt zurück.",
        "Die Liebe findet dich, wenn du es am wenigsten erwartest.",
        "Erfolge entstehen aus kleinen Schritten.",
        "Achte auf dein Bauchgefühl.",
        "Die besten Dinge im Leben sind kostenlos.",
        "Jeder Weg beginnt mit dem ersten Schritt.",
        "Vertrauen ist der Anfang von allem.",
        "Ein freundliches Wort kann Wunder wirken.",
        "Sei offen für neue Erfahrungen.",
        "Dein Herz kennt den Weg.",
        "Ergreife die Gelegenheit beim Schopf.",
        "Das Leben ist zu kurz für negative Gedanken.",
        "Deine Träume sind es wert, verfolgt zu werden.",
        "Jeder neue Tag ist ein unbeschriebenes Blatt.",
        "Lass dich von der Schönheit des Lebens inspirieren.",
        "Geduld ist eine Tugend.",
        "Der Erfolg kommt zu denen, die daran glauben.",
        "Ein positiver Geist zieht positive Dinge an.",
        "Sei dankbar für die kleinen Dinge im Leben.",
        "Das Glück findet dich, wenn du es am wenigsten erwartest.",
        "Veränderungen sind der Anfang von etwas Neuem.",
        "Vertrauen in dich selbst ist der Schlüssel zum Erfolg.",
        "Jeder Tag birgt neue Möglichkeiten.",
        "Sei du selbst und vertraue darauf, dass du genug bist.",
        "Die besten Abenteuer beginnen mit einem Schritt ins Unbekannte.",
        "Glück ist, wenn Vorbereitung auf Gelegenheit trifft.",
        "Lass dich von deinen Träumen leiten.",
        "Ein freundliches Herz zieht Freundlichkeit an.",
        "Deine Zukunft wird von dem bestimmt, was du heute tust.",
        "Sei offen für die Wunder des Lebens.",
        "Jeder Moment ist eine neue Chance.",
        "Glaube an die Magie des Anfangs.",
        "Ein positiver Geist schafft positive Ergebnisse.",
        "Lass dein Licht hell strahlen.",
        "Die besten Dinge im Leben kommen unerwartet.",
        "Vertraue auf den Fluss des Lebens.",
        "Du bist stärker als du denkst.",
        "Jeder Tag ist eine neue Gelegenheit.",
        "Deine Träume sind es wert, verfolgt zu werden.",
        "Sei dankbar für die Reise, nicht nur das Ziel.",
        "Veränderungen bringen neue Möglichkeiten.",
        "Lass die Vergangenheit los und schaue nach vorn.",
        "Erfolg ist das Ergebnis von harter Arbeit.",
        "Glaube an deine Fähigkeiten.",
        "Dein inneres Licht strahlt am hellsten.",
        "Jeder Tag birgt eine neue Möglichkeit.",
        "Genieße die kleinen Freuden des Lebens.",
        "Gute Dinge kommen zu denen, die warten.",
        "Dein Mut wird belohnt werden.",
        "Die Zukunft ist, was du daraus machst.",
        "Lächle und die Welt lächelt zurück.",
        "Die Liebe findet dich, wenn du es am wenigsten erwartest.",
        "Erfolge entstehen aus kleinen Schritten.",
        "Achte auf dein Bauchgefühl.",
        "Die besten Dinge im Leben sind kostenlos.",
        "Jeder Weg beginnt mit dem ersten Schritt.",
        "Vertrauen ist der Anfang von allem.",
        "Ein freundliches Wort kann Wunder wirken.",
        "Sei offen für neue Erfahrungen.",
        "Dein Herz kennt den Weg.",
        "Ergreife die Gelegenheit beim Schopf.",
        "Das Leben ist zu kurz für negative Gedanken.",
        "Deine Träume sind es wert, verfolgt zu werden.",
        "Jeder neue Tag ist ein unbeschriebenes Blatt.",
        "Lass dich von der Schönheit des Lebens inspirieren.",
        "Geduld ist eine Tugend."
    ]
    index = Math.floor(Math.random() * FortuneCookie.length);
    document.getElementById("FortuneCookieTextDisplay").innerHTML = FortuneCookie[index];

}
