async function Fortune() {

    /*    const response = await fetch("https://inspirobot.me/api?generateFlow=1");
        const movies = await response.json();
        console.log(movies);
    */
    const FortuneCookie = [
        "Eine Reise von tausend Meilen beginnt mit einem einzigen Schritt.",
        "Das Glück liegt oft in kleinen Dingen.",
        "Folge deinem Herzen, es kennt den Weg.",
        "Eine neue Herausforderung bringt neue Möglichkeiten.",
        "Der Erfolg kommt zu denen, die daran glauben.",
        "Jeder Tag ist ein Geschenk, nutze ihn weise.",
        "Vertrauen ist der Schlüssel zu allen Türen.",
        "Ein Lächeln öffnet Herzen.",
        "Geduld bringt Rosen.",
        "Veränderungen bedeuten Wachstum.",
        "Dein Mut wird belohnt werden.",
        "Die beste Zeit ist jetzt.",
        "Freunde sind der Schatz des Lebens.",
        "Glaube an Wunder, sie geschehen jeden Tag.",
        "Jeder Moment zählt.",
        "Sei du selbst, alle anderen gibt es schon.",
        "Ein neuer Anfang wartet auf dich.",
        "Jeder Tag ist eine neue Chance.",
        "Sei dankbar für das, was du hast.",
        "Die Liebe wird dir neue Türen öffnen.",
        "Lebe im Hier und Jetzt.",
        "Wer wagt, gewinnt.",
        "Kleine Taten können Großes bewirken.",
        "Du bist der Architekt deines Lebens.",
        "Veränderungen bringen frischen Wind.",
        "Lass die Vergangenheit los und schau nach vorn.",
        "Erfolg ist das Ergebnis harter Arbeit.",
        "Glaube an deine Träume.",
        "Dein inneres Licht strahlt am hellsten.",
        "Jeder Tag birgt eine neue Möglichkeit.",
        "Genieße die kleinen Freuden des Lebens.",
        "Gute Dinge kommen zu denen, die warten.",
        "Dein Mut wird belohnt werden.",
        "Die Zukunft ist, was du daraus machst.",
        "Lächle und die Welt lächelt zurück.",
        "Die Liebe findet dich, wenn du es am wenigsten erwartest.",
        "Erfolge entstehen aus kleinen Schritten.",
        "Achte auf dein Bauchgefühl.",
        "Die besten Dinge im Leben sind kostenlos.",
        "Jeder Weg beginnt mit dem ersten Schritt.",
        "Vertrauen ist der Anfang von allem.",
        "Ein freundliches Wort kann Wunder wirken.",
        "Sei offen für neue Erfahrungen.",
        "Dein Herz kennt den Weg.",
        "Ergreife die Gelegenheit beim Schopf.",
        "Das Leben ist zu kurz für negative Gedanken.",
        "Deine Träume sind es wert, verfolgt zu werden.",
        "Jeder neue Tag ist ein unbeschriebenes Blatt.",
        "Lass dich von der Schönheit des Lebens inspirieren.",
        "Geduld ist eine Tugend.",
        "Der Erfolg kommt zu denen, die daran glauben.",
        "Ein positiver Geist zieht positive Dinge an.",
        "Sei dankbar für die kleinen Dinge im Leben.",
        "Das Glück findet dich, wenn du es am wenigsten erwartest.",
        "Veränderungen sind der Anfang von etwas Neuem.",
        "Vertrauen in dich selbst ist der Schlüssel zum Erfolg.",
        "Jeder Tag birgt neue Möglichkeiten.",
        "Sei du selbst und vertraue darauf, dass du genug bist.",
        "Die besten Abenteuer beginnen mit einem Schritt ins Unbekannte.",
        "Glück ist, wenn Vorbereitung auf Gelegenheit trifft.",
        "Lass dich von deinen Träumen leiten.",
        "Ein freundliches Herz zieht Freundlichkeit an.",
        "Deine Zukunft wird von dem bestimmt, was du heute tust.",
        "Sei offen für die Wunder des Lebens.",
        "Jeder Moment ist eine neue Chance.",
        "Glaube an die Magie des Anfangs.",
        "Ein positiver Geist schafft positive Ergebnisse.",
        "Lass dein Licht hell strahlen.",
        "Die besten Dinge im Leben kommen unerwartet.",
        "Vertraue auf den Fluss des Lebens.",
        "Du bist stärker als du denkst.",
        "Jeder Tag ist eine neue Gelegenheit.",
        "Deine Träume sind es wert, verfolgt zu werden.",
        "Sei dankbar für die Reise, nicht nur das Ziel.",
        "Veränderungen bringen neue Möglichkeiten.",
        "Lass die Vergangenheit los und schaue nach vorn.",
        "Erfolg ist das Ergebnis von harter Arbeit.",
        "Glaube an deine Fähigkeiten.",
        "Dein inneres Licht strahlt am hellsten.",
        "Jeder Tag birgt eine neue Möglichkeit.",
        "Genieße die kleinen Freuden des Lebens.",
        "Gute Dinge kommen zu denen, die warten.",
        "Dein Mut wird belohnt werden.",
        "Die Zukunft ist, was du daraus machst.",
        "Lächle und die Welt lächelt zurück.",
        "Die Liebe findet dich, wenn du es am wenigsten erwartest.",
        "Erfolge entstehen aus kleinen Schritten.",
        "Achte auf dein Bauchgefühl.",
        "Die besten Dinge im Leben sind kostenlos.",
        "Jeder Weg beginnt mit dem ersten Schritt.",
        "Vertrauen ist der Anfang von allem.",
        "Ein freundliches Wort kann Wunder wirken.",
        "Sei offen für neue Erfahrungen.",
        "Dein Herz kennt den Weg.",
        "Ergreife die Gelegenheit beim Schopf.",
        "Das Leben ist zu kurz für negative Gedanken.",
        "Deine Träume sind es wert, verfolgt zu werden.",
        "Jeder neue Tag ist ein unbeschriebenes Blatt.",
        "Lass dich von der Schönheit des Lebens inspirieren.",
        "Geduld ist eine Tugend."
    ]
    index = Math.floor(Math.random() * FortuneCookie.length);
    document.getElementById("FortuneCookieTextDisplay").innerHTML = FortuneCookie[index];

}

async function Misfortune() {
const Misfortunecookie = [
    "In der Dunkelheit meines Geistes gibt es keinen Ausweg.",
    "Schmerz ist der ständige Begleiter meiner einsamen Seele.",
    "Jeder Tag fühlt sich an wie eine endlose Folter.",
    "Meine Gedanken sind Gefängniszellen ohne Schlüssel.",
    "Die Welt scheint nur aus Leid und Qual zu bestehen.",
    "Jeder Atemzug ist eine Erinnerung an unerträglichen Schmerz.",
    "Das Licht am Ende des Tunnels scheint nur eine Illusion zu sein.",
    "Mein Herz ist ein Schlachtfeld der Verzweiflung.",
    "Der Schatten der Depression erstickt jede Hoffnung.",
    "Meine Seele ist in endloser Dunkelheit gefangen.",
    "In der Stille finde ich nur die Schreie meiner inneren Dämonen.",
    "Meine Tränen sind ein stummer Schrei nach Erlösung.",
    "Die Last der Welt zerbricht langsam meinen Geist.",
    "Mein Lächeln ist eine Maske, die die tiefe Traurigkeit verbirgt.",
    "Ich wandle durch das Leben wie ein Schatten ohne Substanz.",
    "Meine Gedanken sind ein endloses Labyrinth des Leidens.",
    "Die Welt ist ein grauer Ort, leer und trostlos.",
    "Jeder neue Tag bringt nur mehr Qual und Schmerz.",
    "Mein Geist ist ein ständiges Schlachtfeld der Verzweiflung.",
    "Die Kälte der Einsamkeit durchdringt meine Seele.",
    "Meine Wunden sind unsichtbar, aber sie bluten stetig.",
    "Ich bin ein Gefangener meiner eigenen Gedanken.",
    "Die Dunkelheit meiner Seele verschlingt jedes Licht.",
    "Mein Herz schlägt, aber es fühlt sich leer an.",
    "Die Schmerzen des Lebens lassen mich in ständiger Angst leben.",
    "Jeder Schritt vorwärts fühlt sich an wie ein Schritt in den Abgrund.",
    "Mein Geist ist in einem endlosen Albtraum gefangen.",
    "Ich schreie, aber niemand hört mich in der Leere.",
    "Die Welt ist ein Ort der endlosen Qual.",
    "Jeder Tag ist ein weiterer Kampf gegen die Dunkelheit.",
    "Meine Seele ist von einem undurchdringlichen Nebel umhüllt.",
    "Der Schmerz in meinem Herzen ist unerträglich.",
    "Die Last der Depression zerquetscht mein Dasein.",
    "Meine Träume sind nur weitere Schauplätze der Folter.",
    "In meinem Kopf herrscht ein Sturm der Verzweiflung.",
    "Mein Leben fühlt sich an wie eine endlose Nacht.",
    "Die Schreie meines Herzens verhallen ungehört.",
    "Jeder Atemzug bringt nur mehr Schmerz und Leid.",
    "Mein Geist ist zerschmettert von der Last des Lebens.",
    "Ich bin ein Schatten meiner selbst, verloren in der Dunkelheit.",
    "Die Welt ist ein Ort der Trostlosigkeit und Leere.",
    "Jeder neue Tag ist eine weitere Prüfung meiner Belastbarkeit.",
    "Mein Herz ist ein ewiger Quell des Schmerzes.",
    "Die Dämonen in meinem Kopf lassen mich nicht los.",
    "Jeder Gedanke bringt nur mehr Qual und Verzweiflung.",
    "Ich bin gefangen in einem endlosen Kreis des Leidens.",
    "Die Dunkelheit ist mein ständiger Begleiter.",
    "Meine Seele ist zerschlagen und zerbrochen.",
    "Jeder Moment ist ein weiterer Schritt in den Abgrund.",
    "Die Welt ist ein endloses Meer der Verzweiflung.",
    "Mein Geist ist gefangen in einem Netz aus Schmerz.",
    "Die Schreie meines Herzens sind stumm und unerhört.",
    "Jeder Tag ist ein weiterer Kampf gegen die inneren Dämonen.",
    "Mein Herz ist ein Gefängnis der Traurigkeit.",
    "Die Dunkelheit erstickt jede Hoffnung in mir.",
    "Mein Leben ist eine endlose Spirale des Leids.",
    "Die Welt ist ein kalter und trostloser Ort.",
    "Mein Geist ist von den Ketten der Depression gefesselt.",
    "Jeder Atemzug ist eine Erinnerung an meinen Schmerz.",
    "Die Last der Welt liegt schwer auf meinen Schultern.",
    "Mein Herz schreit nach Erlösung, doch es bleibt unerhört.",
    "Die Dunkelheit verschlingt meine Seele.",
    "Meine Gedanken sind ein endloser Strudel des Leids.",
    "Jeder Tag ist ein weiterer Schritt in den Abgrund.",
    "Die Welt ist ein Ort der ständigen Qual.",
    "Mein Geist ist ein Gefängnis aus Angst und Schmerz.",
    "Die Schreie meines Herzens sind unaufhörlich.",
    "Jeder Moment ist ein weiterer Tropfen in das Meer des Leids.",
    "Die Dunkelheit ist allumfassend und unerbittlich.",
    "Meine Seele ist in einem endlosen Krieg gefangen.",
    "Jeder Atemzug bringt nur mehr Schmerz und Qual.",
    "Die Last der Depression drückt mich zu Boden.",
    "Mein Herz ist ein ewiger Quell der Verzweiflung.",
    "Die Dämonen in meinem Kopf lassen mich nicht los.",
    "Jeder Gedanke ist ein weiterer Nagel in meinem Sarg.",
    "Ich bin gefangen in einem Netz aus Leid und Schmerz.",
    "Die Dunkelheit erstickt jede Hoffnung in mir.",
    "Meine Seele ist zerschlagen und zerbrochen.",
    "Jeder Moment ist ein weiterer Schritt in den Abgrund.",
    "Die Welt ist ein endloses Meer der Verzweiflung.",
    "Mein Geist ist gefangen in einem Labyrinth aus Angst.",
    "Die Schreie meines Herzens verhallen ungehört.",
    "Jeder Tag ist ein weiterer Kampf gegen die inneren Dämonen.",
    "Mein Herz ist ein Gefängnis der Traurigkeit.",
    "Die Dunkelheit verschlingt meine Seele.",
    "Mein Leben ist eine endlose Spirale des Leids.",
    "Die Welt ist ein kalter und trostloser Ort.",
    "Mein Geist ist von den Ketten der Depression gefesselt.",
    "Jeder Atemzug ist eine Erinnerung an meinen Schmerz.",
    "Die Last der Welt liegt schwer auf meinen Schultern.",
    "Mein Herz schreit nach Erlösung, doch es bleibt unerhört.",
    "Die Dunkelheit verschlingt meine Seele.",
    "Meine Gedanken sind ein endloser Strudel des Leids.",
    "Jeder Tag ist ein weiterer Schritt in den Abgrund.",
    "Die Welt ist ein Ort der ständigen Qual.",
    "Mein Geist ist ein Gefängnis aus Angst und Schmerz.",
    "Die Schreie meines Herzens sind unaufhörlich.",
    "Jeder Moment ist ein weiterer Tropfen in das Meer des Leids.",
    "Die Dunkelheit ist allumfassend und unerbittlich.",
    "Meine Seele ist in einem endlosen Krieg gefangen."
]
index = Math.floor(Math.random() * Misfortunecookie.length);
    document.getElementById("MisFortuneCookieTextDisplay").innerHTML = Misfortunecookie[index];
}